#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

putenv('FZKC_PROJECT_NAME=' . basename(realpath(__DIR__ . '/../../')));
putenv('FZKC_CASTLE_NAME=' . basename(__DIR__));

$lines = file(__DIR__ . '/../../docker/dev/.env', FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);

foreach ($lines as $var) {
    putenv($var);
}

$lines = file(__DIR__ . '/_docker/dev/.env', FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);

foreach ($lines as $var) {
    putenv($var);
}

// Bootstrap Laravel and handle the command...
$status = (require_once __DIR__.'/bootstrap/app.php')
    ->handleCommand(new ArgvInput);

exit($status);
