services:
  castle:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${FZKC_PROJECT_NAME}-${FZKC_CASTLE_NAME}-castle-container
    environment:
        OCTANE_HOST: "${OCTANE_HOST}"
        OCTANE_PORT: ${OCTANE_PORT}
        OCTANE_WATCH: "${OCTANE_WATCH}"
    hostname: ${FZKC_CASTLE_NAME}.${FZKC_PROJECT_NAME}.space
    restart: always
    volumes:
      - ./../../.:/app
    ports:
      - "${FZKC_CASTLE_PORT}:${OCTANE_PORT}"
    networks:
      - fzkc-net01
    #  fzkc-net01:
    #    ipv4_address: 
    #
    # you must add a DNS entry into /etc/hosts (with "127.0.0.1" as ip address) for the resolution of the containers services's hostname 
    # by the host (HOST -> CONTAINERS)
    #
    # N.B. Instead of add extra_hosts or similar, add the entries inside the coredns dbs
    #extra_hosts:
    #  - ""
  