services:
  {%% FZKC_CASTLE_NAME %%}-castle:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${FZKC_PROJECT_NAME}-${FZKC_CASTLE_NAME}-castle-container
    env_file:
      - ./../../../../docker/dev/.env
      - ./.env
    environment:
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
      FZKC_PROJECT_NAME: ${FZKC_PROJECT_NAME}
      FZKC_CASTLE_NAME: ${FZKC_CASTLE_NAME}
    hostname: ${FZKC_CASTLE_NAME}.${FZKC_PROJECT_NAME}.space
    dns:
      - ${FZKC_NETWORK_DNS_IP}
    restart: always
    volumes:
      - ./../../.:/app
    ports:
      - "${FZKC_CASTLE_PORT}:${OCTANE_PORT}"
    networks:
      - fzkc-net01
    #  fzkc-net01:
    #    ipv4_address: 
    #
    # you must add a DNS entry into /etc/hosts (with "127.0.0.1" as ip address) for the resolution of the containers services's hostname 
    # by the host (HOST -> CONTAINERS)
    #
    # N.B. Instead of add extra_hosts or similar, add the entries inside the coredns dbs
    #extra_hosts:
    #  - ""

networks:
  fzkc-net01:
    ipam:
      driver: default
      config:
        - subnet: ${FZKC_NETWORK}
          gateway: ${FZKC_NETWORK_GATEWAY}
  